---
# TODO(inc0): Gates don't seem to have ufw executable, check for it instead of ignore errors
- name: Set firewall default policy
  become: True
  ufw:
    state: disabled
    policy: allow
  when: ansible_os_family == 'Debian'
  ignore_errors: yes

- name: Check if firewalld is installed
  command: rpm -q firewalld
  register: firewalld_check
  failed_when: firewalld_check.rc > 1
  when: ansible_os_family == 'RedHat'

- name: Disable firewalld
  become: True
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - firewalld
  when:
    - ansible_os_family == 'RedHat'
    - firewalld_check.rc == 0

- name: Install yum packages
  package:
    name: "{{ item }}"
    state: present
  become: True
  with_items: "{{ redhat_pkg_install }}"
  when: ansible_os_family == 'RedHat'


- name: Install python toolkit
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: -i http://192.168.0.13:8081/repository/stack/simple --trusted-host 192.168.0.13
    virtualenv: "{{ virtualenv is none | ternary(omit, virtualenv) }}"
    virtualenv_site_packages: "{{ virtualenv is none | ternary(omit, virtualenv_site_packages) }}"
  become: True
  with_items: "{{ python_pkg_install }}"

- name: Ensure virtualenv has correct ownership
  file:
    path: "{{ virtualenv }}"
    recurse: True
    state: directory
    owner: kolla
    group: kolla
  become: True
  when: virtualenv is not none

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ ubuntu_pkg_removals }}"
  become: True
  when: ansible_distribution|lower == "ubuntu"

- name: Remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ redhat_pkg_removals }}"
  become: True
  when: ansible_os_family == 'RedHat'
