---
- name: disable selinux
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS'

- name: reboot
  reboot:
    reboot_timeout: 1200
  when:
    - inventory_hostname in group['new']
    - reset_network_force

