---
- name: disable selinux
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS'

- name: reboot
  reboot:
  when:
    - inventory_hostname in groups['new']
    - reset_network_force

