---
docker_kernel_min_version: '0'

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
# https://yum.dockerproject.org/repo/main/centos/7
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-ce


docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"

