---
docker_kernel_min_version: '3.10'

# https://download.docker.com/linux/ubuntu/
docker_versioned_pkg:
  'latest': docker-ce

docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

