---
docker_version: 'latest'

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

dockerproject_repo_key_info:
  repo_keys:

dockerproject_repo_info:
  repos:

docker_dns_servers_strict: true

docker_container_storage_setup: false

# Used to set docker daemon iptables options
docker_iptables_enabled: "false"
