---
- name: Make sure the include line is there in interfaces file
  lineinfile:
    regexp: "^source /etc/network/interfaces.d/*"
    line: "source /etc/network/interfaces.d/*"
    dest: /etc/network/interfaces
    state: present
    insertafter: EOF
  when: ansible_os_family == "Debian"

- name: Create the directory for interface cfg files
  file:
    path: /etc/network/interfaces.d
    state: directory
  when: ansible_os_family == "Debian"
