---
- name: restart network
  systemd:
    name: '{{ item }}'
    state: restarted
  with_items:
    - dbus
    - systemd-logind
    - NetworkManager
    - network
  when: ansible_os_family == 'RedHat'
