---
- name: restart network
  systemd:
    name: '{{ item }}'
    state: restarted
  with_items:
    - dubs
    - NetworkManager
    - network
    - systemd-logind
  when: ansible_os_family == 'RedHat'
