---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: install pkgs
  include: install.yml

- name: reflush network server
  include: flushnetwork.yml

- name: clean os network options
  include: clean.yml

- name: set ethernet
  include: ethernet.yml

- name: set bridge
  include: bridge.yml

- name: set bond
  include: bond.yml

