---

###################
# Kolla options
###################
# Valid options are [ COPY_ONCE, COPY_ALWAYS ]
config_strategy: "COPY_ALWAYS"

# The directory to merge custom config files the kolla's config files
node_custom_config: "/etc/dire/config"

# The project to generate configuration files for
project: ""

# The "temp" files that are created before merge need to stay persistent due
# to the fact that ansible will register a "change" if it has to create them
# again. Persistent files allow for idempotency
container_config_directory: "/var/lib/dire/config_files"

# The directory to store the config files on the destination node
node_config_directory: "/etc/dire/{{ project }}"

# Valid options are ['centos', 'debian', 'oraclelinux', 'rhel', 'ubuntu']
kolla_base_distro: "ubuntu"
# Valid options are [ binary, source ]
kolla_install_type: "binary"

# The group which own node_config_directory, you can use a non-root
# user to deploy kolla
config_owner_user: "dire"
config_owner_group: "dire"


####################
# OpenStack options
####################
openstack_release: "queens"


#################
# respostory url
#################
deploy_host: deploy.stack.slancer
certs_repo_host: '{{deploy_host}}'
apt_repo_host: '{{deploy_host}}'
yum_repo_host: '{{deploy_host}}'
pip_repo_host: '{{deploy_host}}'
certs_repo_url: 'http://{{certs_repo_host}}/repository/certs'
yum_repo_url: 'http://{{yum_repo_host}}/repository/yum'
apt_sources_url: 'http://{{apt_repo_host}}/repository'
pip_repo_url: 'http://{{pip_repo_host}}/repository/pypi/simple'


################
# Chrony options
################
# A list contains ntp servers
external_ntp_servers:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org


####################
# Database options
####################
docker_registry: "{{deploy_host}}"
docker_namespace: "kolla"
docker_registry_username: "admin"
docker_registry_password: "admin123"

# Valid options are [ never, on-failure, always, unless-stopped ]
docker_restart_policy: "unless-stopped"

# '0' means unlimited retries
docker_restart_policy_retry: "10"

# Common options used throughout Docker
docker_common_options:
  auth_password: "{{ docker_registry_password }}"
  auth_registry: "{{ docker_registry }}"
  auth_username: "{{ docker_registry_username }}"
  environment:
    KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
  restart_policy: "{{ docker_restart_policy }}"
  restart_retries: "{{ docker_restart_policy_retry }}"


####################
# Dimensions options
####################
# Dimension options for Docker Containers
default_container_dimensions: {}
