- name: Ensure sudo group is present
  group:
    name: sudo
    state: present
  become: True

- name: Ensure kolla group is present
  group:
    name: "{{ kolla_group }}"
    state: present
  become: True
  when: create_kolla_user | bool

- name: Create kolla user
  user:
    name: "{{ kolla_user }}"
    state: present
    group: "{{ kolla_group }}"
    groups: "sudo,docker"
    shell: "/bin/bash"
    append: true
  become: True
  when: create_kolla_user | bool

- name: Add public key to kolla user authorized keys
  authorized_key:
    user: "{{ kolla_user }}"
    key: "{{ kolla_ssh_key.public_key }}"
  become: True
  when: create_kolla_user | bool

- name: Create sudoers profile for user kolla
  file:
    path: /etc/sudoers.d/kolla-ansible-users
    state: touch
  become: True
  when: create_kolla_user_sudoers | bool

- name: Grant kolla user passwordless sudo
  lineinfile:
    dest: /etc/sudoers.d/kolla-ansible-users
    state: present
    regexp: '^{{ kolla_user }}'
    line: '{{ kolla_user }} ALL=(ALL) NOPASSWD: ALL'
  become: True
  when: create_kolla_user_sudoers | bool

- name: Grant sudo group no tty
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^Defaults.*requiretty$'
    line: 'Defaults:%sudo !requiretty'
  become: True
  when: create_kolla_user_sudoers | bool

- name: Ensure node_config_directory directory exists for user kolla
  file:
    path: "{{ node_config_directory }}"
    state: directory
    recurse: yes
    owner: "{{ kolla_user }}"
    group: "{{ kolla_group }}"
    mode: 0755
  become: True
  when: create_kolla_user | bool

- name: Ensure node_config_directory directory exists
  file:
    path: "{{ node_config_directory }}"
    state: directory
    recurse: yes
    mode: 0644
  become: True
  when: not create_kolla_user | bool
