---
- name: Set Host Name
  hostname:
    name: '{{inventory_hostname}}'

- name: Ensure localhost in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1.*"
    line: "127.0.0.1 localhost"
    state: present

- name: Generate /etc/hosts for all of the nodes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE GENERATED HOSTS"
    block: |
        {{ deploy_ip }} {{ deploy_host }}
        {% for host in groups['all'] %}
        {{ hostvars[host]['ansible_host']}} {{ hostvars[host]['ansible_hostname'] }}
        {% endfor %}
    create: true
