---
- name: Make Registry Crt Dir
  file:
    dest: '/etc/docker/certs.d/{{docker_registry}}'
    state: directory

- name: Post Client Registry CRT File
  get_url:
    url: 'http://{{certs_repo_host}}/certs/keystore.crt'
    dest: '/etc/docker/certs.d/{{docker_registry}}'
