---
- name: update os
  hosts:
    - all
  become: true
  roles:
    - {role: facts, tags: always }
    - {role: sshd, tags: sshd ,
        when: inventory_hostname in groups.new }
    - {role: init, kolla_action: deploy, tags: init }
    - {role: repository, tags: repository,
        when: inventory_hostname in groups.new }
    - {role: hosts, tags: hosts }
    - {role: interfaces, tags: interfaces,
        when: inventory_hostname in groups.new}
    - {role: docker, tags: docker,
        when: inventory_hostname in groups.new}
    - {role: dns, tags: dns }
    - {role: user, tags: user }
    - {role: python, tags: python }
    - {role: firewall, tags: firewall }
    - {role: ceph, tags: ceph }
    - {role: chrony, kolla_action: deploy, tags: chrony }
    - {role: timezone, tags: timezone }
    - {role: post, tags: post }
