---
- name: remove yum repo
  file:
    path: /etc/yum.repos.d/
    state: absent
  become: True

- name: Ensure yum repos directory exists
  file:
    path: /etc/yum.repos.d/
    state: directory
    recurse: yes
  become: True

- name: Enable steam repo yum
  become: True
  template:
    src: steam_yum_repo.j2
    dest: /etc/yum.repos.d/steam.repo
