---
- name: remove yum repo
  file:
    path: /etc/yum.repos.d/
    state: absent

- name: Ensure yum repos directory exists
  file:
    path: /etc/yum.repos.d/
    state: directory
    recurse: yes

- name: add steam repo yum
  shell: |
      echo "[steam-repo]
      name=Docker main Repository
      baseurl={{yum_repo_url}}
      enabled=1
      gpgcheck=0" > /etc/yum.repos.d/steam.repo

- name: yum update cache
  yum:
    update_cache: yes

- name: install rehat package
  yum:
    name: '{{item}}'
  with_items: '{{redhat_pkg_install}}'
