---
- raw: grep '^{{ deploy_ip }} *{{ deploy_host }}' /etc/hosts
  register: hosts_enable
  ignore_errors: True

- shell: sed -i '$a\{{ deploy_ip }} {{ deploy_host }}' /etc/hosts
  when: hosts_enable.failed
