---
- raw: sed -i '/{{ deploy_host }}/d' /etc/hosts
  when: deploy_host is defined

- raw: sed -i '$a\{{ deploy_ip }} {{ deploy_host }}' /etc/hosts
  when: deploy_host is defined and deploy_ip is defined

- raw: sed -i '/{{ docker_registry }}/d' /etc/hosts
  when: docker_registry is defined and external_docker_registry_enabled

- raw: sed -i '$a\{{ docker_registry_ip }} {{ docker_registry }}' /etc/hosts
  when: docker_registry is defined and docker_registry_ip is defined and external_docker_registry_enabled