---
- raw: sed -i '/{{ deploy_host }}/d' /etc/hosts
  when: deploy_host is defined

- raw: sed -i '$a\{{ deploy_ip }} {{ deploy_host }}' /etc/hosts
  when: deploy_host is defined and deploy_ip is defined
